enum UsuarioPermission {
	LER_USUARIO = 'LER_USUARIO',
	LER_USUARIO_GESTOR = 'LER_USUARIO_GESTOR',
	MODIFICAR_USUARIO_PUBLIC = 'MODIFICAR_USUARIO_PUBLIC',
	MODIFICAR_USUARIO = 'MODIFICAR_USUARIO',
	MODIFICAR_USUARIO_GESTOR = 'MODIFICAR_USUARIO_GESTOR'
}
   
export default UsuarioPermission;