export enum statusRegistroEnum {
    CANCELADO = "CANCELADO",
    CONCLUIDA = "CONCLUIDA",
    FECHADO_AUTOMATICO_PENDENTE = "FECHADO AUTOMÁTICO PENDENTE",
    FECHADO_COM_SUCESSO = "FECHADO COM SUCESSO",
    FECHADO_SEM_SUCESSO = "FECHADO SEM SUCESSO",
    FECHADO_COM_SOLUÇÃO_ALTERNATIVA = "FECHADO COM SOLUÇÃO ALTERNATIVA"
}